name: Release

on:
  workflow_dispatch:
    inputs:
      publish:
        description: 'Publish to Maven Central.'
        required: true
        type: boolean
        default: false
      version-name:
        description: 'Version name.'
        required: false
        type: string
      release-body:
        description: 'Release notes.'
        required: false
        type: string
      result:
        description: 'publish result'
        required: true
        type: number

jobs:
  publish:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.publish == 'true' }}
    steps:
      - id: publish
        run: |
          echo "Publishing..."
          exit ${{ github.event.inputs.result }}

  release:
    if: ${{ github.event.inputs.publish == 'false' || success() }}
    needs: [publish]
    uses: jenly1314/actions/.github/workflows/reusable-release.yml@v2
    with:
      version-name: ${{ github.event.inputs.version-name }}
      release-body: ${{ github.event.inputs.release-body }}
